#!/bin/sh
#
#  Update build number
#
#  Create build.h with an incremented build number and a static version number
#  By Simon Riget @ Paragi 2019 MIT.
#

BUILD_HEADER="build.h"
BUILD_NUMBER_FILE_NAME="build"
VERSION_NUMBER_FILE_NAME="version"


if [ -f "$BUILD_NUMBER_FILE_NAME" ]
then
	. ./$BUILD_NUMBER_FILE_NAME
else
	BUILD_NUMBER=0
fi

if [ -f "$VERSION_NUMBER_FILE_NAME" ]
then
	. ./$VERSION_NUMBER_FILE_NAME
else
  VERSION="0.1.0"
fi

BUILD_NUMBER=$(( $BUILD_NUMBER + 1 ))
DATE=$(date "+%Y-%m-%d")

echo "Generating build number ${BUILD_NUMBER}@$DATE for version $VERSION"


echo "
#
#  Auto generated by update-build.number.sh.
#
BUILD_NUMBER=$BUILD_NUMBER
" > "$BUILD_NUMBER_FILE_NAME"

chmod 775 "$BUILD_NUMBER_FILE_NAME"

echo "
#
#  Auto generated by update-build.number.sh.
#
VERSION=$VERSION
" > "$VERSION_NUMBER_FILE_NAME"

chmod 775 "$VERSION_NUMBER_FILE_NAME"


echo \
"/*==========================================================================*\\
  Auto generated by update-build.number.sh
\\*==========================================================================*/
const char * _version = \"${VERSION} build:${BUILD_NUMBER}@$DATE\";
" > "$BUILD_HEADER"
